### PR TITLE
switch to emotion

### PR DESCRIPTION
**Pull request by caub**
Hey @kkostov 

I think it'd good to switch to emotion if you don't mind, it's smaller, more popular

also added the build of the demo, so that you can link in the project description https://caub.github.io/react-calendar-icon/build/index.html ('caub' should be replaced by 'kkostov' for the main repo)

Edit: seems good, I'm not able to test it well on my app, I get some these react errors https://reactjs.org/warnings/invalid-hook-call-warning.html but I guess once published on npm it'll work

### CODE REVIEW

**Comment by caub** [comment]
fixes #93 and probably #90 too

**Comment by caub** [comment]
demo live here: https://caub.github.io/react-calendar-icon/build/

**Comment by caub** [comment]
I've tested it from another app (npm link or npm i path/to/local/react-calendar-icon) both works well

**Comment by caub** [comment]
the reason there are many changes is I moved demo to be able to run it with react-scripts

**Comment by kkostov** [comment]
Hey @caub, that's awesome work 🤩!

I really don't have enough time to go over the changes at the moment (life stuff...). If you depend on this library, my suggestion would be to fork it.

I also think it makes sense to forego "css-in-js" in favour of creating a plain CSS stylesheet for it. There are no features that require dynamic css and the end result may be even cleaner because it takes advantage of the cascade instead of reliance on JS libraries to generate class names.

**Comment by caub** [comment]
> "css-in-js" in favour of creating a plain CSS stylesheet for it

yea I totally thought about it, but what about the theming feature? css variables I guess

Thanks

Maybe do you mind adding me in this repo, I'll maintain it and publish to npm if you're ok, simpler/cleaner than duplicating in npm

**Comment by caub** [comment]
I'll make a separate PR to switch to pure CSS, and we would increase major version

**Comment by kkostov** [comment]
@caub fair point about theming - it will be inconvenient for folks who already use the ThemeProvider to adapt right away.

I've added you as a collaborator, just tag a release when it's ready to go! Thank you :) !

**Comment by caub** [comment]
Thanks @kkostov I tagged a 0.10.0 release

**Pull request closed without merging**
